# Generated by Django 5.1.6 on 2025-02-23 12:18

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in progress', 'Заполняется'), ('checking', 'На рассмотрении'), ('good', 'Участие в этапе'), ('error', 'Ошибки в заполнении')], default='in progress', max_length=30)),
                ('type', models.CharField(choices=[('school', 'Junior'), ('university', 'Student')], max_length=50)),
                ('participant_status', models.CharField(choices=[('full', 'Одно учебное заведение'), ('mixed', 'Несколько учебных заведений')], max_length=30)),
                ('quaterfinal', models.BooleanField(blank=True, default=False)),
                ('semifinal', models.BooleanField(blank=True, default=False)),
                ('final', models.BooleanField(blank=True, default=False)),
                ('disqualified', models.BooleanField(blank=True, default=False)),
                ('disqual_message', models.TextField(blank=True, null=True)),
                ('system_login', models.CharField(blank=True, max_length=100, null=True)),
                ('system_password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_generated_mail', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coach')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('student_status', models.CharField(choices=[('студент', 'Студент'), ('школьник', 'Школьник'), ('аспирант', 'Аспирант'), ('магистрант', 'Магистрант'), ('др', 'Другое')], max_length=30)),
                ('tshirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('group', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='main.team')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('be', 'Belarussian')], max_length=2)),
                ('translated_text', models.TextField()),
                ('translation_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.translationkey')),
            ],
            options={
                'unique_together': {('translation_key', 'language')},
            },
        ),
    ]
